name: Deploying to OSSRH with Apache Maven
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: OSSRH_USER
        server-password: OSSRH_PASS
        gpg-private-key: ${{ secrets.GPG_PK }}
        gpg-passphrase: GPG_PP

    - run: mvn deploy
      env:
        OSSRH_USER: wk-v
        OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
        GPG_PP: ${{ secrets.GPG_PP }}
